FROM ubuntu:14.04
MAINTAINER Sergio Santoro

RUN apt-get update && apt-get upgrade -y
RUN apt-get remove -y python3
RUN apt-get install -y python python-pip

COPY httpie /root/httpie
RUN cd /root/httpie && make

RUN rm -rf /root/httpie/*
